### ISSUE TITLE
不正なpublickeyを与えるとpanicする

### ISSUE THREAD

**Issue by tignear** [machikado-network/tubuyaita#17]
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: signature::Error { source: Some(PublicKey must be 32 bytes in length) }', src/lib.rs:10:89
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: signature::Error { source: Some(PublicKey must be 32 bytes in length) }', src/lib.rs:10:89
```

**Comment by sizumita** [comment]
related https://github.com/machikado-network/tubuyaita-crypto/issues/3
